# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VirtualassistantUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1920, 1080)
        self.Background_1 = QtWidgets.QLabel(Form)
        self.Background_1.setGeometry(QtCore.QRect(-266, -120, 2631, 1311))
        self.Background_1.setText("")
        self.Background_1.setPixmap(QtGui.QPixmap("Gui/Black_Template.jpg"))
        self.Background_1.setScaledContents(True)
        self.Background_1.setObjectName("Background_1")
        self.Gif_1 = QtWidgets.QLabel(Form)
        self.Gif_1.setGeometry(QtCore.QRect(10, 10, 471, 211))
        self.Gif_1.setText("")
        self.Gif_1.setPixmap(QtGui.QPixmap("Gui/initial.gif"))
        self.Gif_1.setScaledContents(True)
        self.Gif_1.setObjectName("Gif_1")
        self.Background_2 = QtWidgets.QLabel(Form)
        self.Background_2.setGeometry(QtCore.QRect(10, 350, 371, 181))
        self.Background_2.setText("")
        self.Background_2.setPixmap(QtGui.QPixmap("Gui/gyhf.jpg"))
        self.Background_2.setScaledContents(True)
        self.Background_2.setObjectName("Background_2")
        self.Background_3 = QtWidgets.QLabel(Form)
        self.Background_3.setGeometry(QtCore.QRect(10, 600, 371, 181))
        self.Background_3.setText("")
        self.Background_3.setPixmap(QtGui.QPixmap("Gui/gyhf.jpg"))
        self.Background_3.setScaledContents(True)
        self.Background_3.setObjectName("Background_3")
        self.Background_4 = QtWidgets.QLabel(Form)
        self.Background_4.setGeometry(QtCore.QRect(620, 190, 741, 591))
        self.Background_4.setText("")
        self.Background_4.setPixmap(QtGui.QPixmap("Gui/abstract-futuristic-background-blue-glowing-technology-sci-fi-frame-hud-ui_303714-24.jpg"))
        self.Background_4.setScaledContents(True)
        self.Background_4.setObjectName("Background_4")
        self.Gif_2 = QtWidgets.QLabel(Form)
        self.Gif_2.setGeometry(QtCore.QRect(1470, 10, 441, 181))
        self.Gif_2.setText("")
        self.Gif_2.setPixmap(QtGui.QPixmap("Gui/loading-gif.gif"))
        self.Gif_2.setScaledContents(True)
        self.Gif_2.setObjectName("Gif_2")
        self.Background_5 = QtWidgets.QLabel(Form)
        self.Background_5.setGeometry(QtCore.QRect(1550, 250, 361, 331))
        self.Background_5.setText("")
        self.Background_5.setPixmap(QtGui.QPixmap("Gui/abstract-futuristic-background-blue-glowing-technology-sci-fi-frame-hud-ui_303714-24.jpg"))
        self.Background_5.setScaledContents(True)
        self.Background_5.setObjectName("Background_5")
        self.Gif_4 = QtWidgets.QLabel(Form)
        self.Gif_4.setGeometry(QtCore.QRect(1570, 290, 321, 251))
        self.Gif_4.setText("")
        self.Gif_4.setPixmap(QtGui.QPixmap("Gui/Earth.gif"))
        self.Gif_4.setScaledContents(True)
        self.Gif_4.setObjectName("Gif_4")
        self.Background_6 = QtWidgets.QLabel(Form)
        self.Background_6.setGeometry(QtCore.QRect(1640, 710, 271, 121))
        self.Background_6.setText("")
        self.Background_6.setPixmap(QtGui.QPixmap("Gui/Start.png"))
        self.Background_6.setScaledContents(True)
        self.Background_6.setObjectName("Background_6")
        self.Background_7 = QtWidgets.QLabel(Form)
        self.Background_7.setGeometry(QtCore.QRect(1640, 860, 271, 101))
        self.Background_7.setText("")
        self.Background_7.setPixmap(QtGui.QPixmap("Gui/Quit.png"))
        self.Background_7.setScaledContents(True)
        self.Background_7.setObjectName("Background_7")
        self.Gif_3 = QtWidgets.QLabel(Form)
        self.Gif_3.setGeometry(QtCore.QRect(660, 260, 661, 461))
        self.Gif_3.setText("")
        self.Gif_3.setPixmap(QtGui.QPixmap("Gui/42787621ed6d40f0c30f0ae423fc572c.gif"))
        self.Gif_3.setScaledContents(True)
        self.Gif_3.setObjectName("Gif_3")
        self.Gif_6 = QtWidgets.QLabel(Form)
        self.Gif_6.setGeometry(QtCore.QRect(660, 260, 661, 461))
        self.Gif_6.setText("")
        self.Gif_6.setPixmap(QtGui.QPixmap("Gui/6ba174bf48e9b6dc8d8bd19d13c9caa9.gif"))
        self.Gif_6.setScaledContents(True)
        self.Gif_6.setObjectName("Gif_6")
        self.Gif_7 = QtWidgets.QLabel(Form)
        self.Gif_7.setGeometry(QtCore.QRect(660, 260, 661, 451))
        self.Gif_7.setText("")
        self.Gif_7.setPixmap(QtGui.QPixmap("Gui/a7b015d343ad801ad6da8c242dc6ae06.gif"))
        self.Gif_7.setScaledContents(True)
        self.Gif_7.setObjectName("Gif_7")
        self.Text_time = QtWidgets.QTextBrowser(Form)
        self.Text_time.setGeometry(QtCore.QRect(90, 420, 231, 51))
        self.Text_time.setStyleSheet("background-color: Transparent;\n"
"color: rgb(0, 255, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"border-radius: none;")
        self.Text_time.setObjectName("Text_time")
        self.Text_date = QtWidgets.QTextBrowser(Form)
        self.Text_date.setGeometry(QtCore.QRect(70, 670, 261, 51))
        self.Text_date.setStyleSheet("background-color: Transparent;\n"
"color: rgb(0, 255, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"border-radius: none;")
        self.Text_date.setObjectName("Text_date")
        self.Pushbutton_start = QtWidgets.QPushButton(Form)
        self.Pushbutton_start.setGeometry(QtCore.QRect(1650, 730, 251, 91))
        self.Pushbutton_start.setStyleSheet("background-color: Transparent;\n"
"border-radius: none;")
        self.Pushbutton_start.setText("")
        self.Pushbutton_start.setObjectName("Pushbutton_start")
        self.Pushbutton_exit = QtWidgets.QPushButton(Form)
        self.Pushbutton_exit.setGeometry(QtCore.QRect(1640, 870, 261, 81))
        self.Pushbutton_exit.setStyleSheet("background-color: Transparent;\n"
"border-radius: none;")
        self.Pushbutton_exit.setText("")
        self.Pushbutton_exit.setObjectName("Pushbutton_exit")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(560, 790, 881, 192))
        self.textBrowser.setStyleSheet("background-color: Transparent;\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius: none;")
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
